board = Board.new
      board.insert_token_in_column("○",4)
      board.insert_token_in_column("○",4)
      board.insert_token_in_column("○",4)
      board.insert_token_in_column("○",4)
      board.insert_token_in_column("○",4)
      board.insert_token_in_column("○",5)
      board.insert_token_in_column("○",5)
      board.insert_token_in_column("○",5)
      board.insert_token_in_column("○",5)
      board.insert_token_in_column("○",6)
      board.insert_token_in_column("○",6)
      board.insert_token_in_column("○",6)
      board.insert_token_in_column("○",7)
      board.insert_token_in_column("○",7)
      board.insert_token_in_column("●",4)
      board.insert_token_in_column("●",5)
      board.insert_token_in_column("●",6)
      auxiliar_array = board.insert_token_in_column("●",7)
      board.display